---
# tasks file for ansible-role-proxy

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: configure proxy for the system
  template:
    owner: "{{owner}}"
    group: "{{group}}"
    mode:  "{{mode}}"
    src:   "{{src}}"
    dest:  "{{dest}}"

- fail: msg="server and port parameters are mandatory"
  failed_when: server == "" or port == ""

