---
# tasks file for ansible-role-proxy

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: configure proxy for the system
  template:
    - owner: {{owner}}
    - group: {{group}}
    - mode:  {{mode}}
    - src:   {{proxy_src}}
    - dest:  {{proxy_dest}}
